# Site settings
site: Flake
title: Flake Blog
keywords: flake, blog
description: >-
  Hobbies and interests of Devin Flake
lang: en-US
timezone:  Mountain/Boise
repo: https://github.com/flakeman2/Ephesus # site repo [optional]
google_verify:      3B0vcgPJX7cXB-d8b6IRiEdvR4sv8sFm1IgaU39LT2k # Put your Google Verification here
google_analytics:   G-ZRZG7LLQ0G # Put your Google Analytics code
disqus-identifier:  devinflake # Your disque shortname, see https://disqus.com/admin/install/platforms/universalcode/

# Author settings
author:
  name: <a href="https://devinflake.com/">Devin Flake</a>
  bio: Site Reliability Engineer @<a href="https://www.adobe.com/">Adobe</a> <br> GNU/Linux + Open Source
  picture: assets/images/profile.jpg 
  github: flakeman2 # github username
  twitter: flakeman2 # twitter username
  facebook: flakeman2 # facebook username
  instagram: flakeman2 # instagram username
  youtube: https://www.youtube.com/channel/UC_dRVgkvwvw7iC1xisdzP_w # youtube username
  linkedin: devinflake # linkedin username
  email: flakeman2@hotmail.com # email adress


# URL settings
url: "https://blog.devinflake.com" # Domain Name of host. [username].github.io for github pages
permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
paginate: 20
paginate_path: "/page/:num"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false
